SHARED_HTML = shared/busha_pay_checkout.html
SHARED_ICONS_DIR = shared/icons

# Copy shared assets into each SDK
.PHONY: sync
sync:
	@mkdir -p flutter/assets && cp $(SHARED_HTML) flutter/assets/busha_pay_checkout.html
	@mkdir -p react-native/assets && cp $(SHARED_HTML) react-native/assets/busha_pay_checkout.html
	@mkdir -p ios/Sources/BushaPay/Resources && cp $(SHARED_HTML) ios/Sources/BushaPay/Resources/busha_pay_checkout.html
	@node -e "const fs=require('fs'); const html=fs.readFileSync('$(SHARED_HTML)','utf8'); fs.writeFileSync('react-native/src/checkout-html.ts', '// Auto-generated by \`make sync\` from $(SHARED_HTML).\n// Do not edit by hand — changes will be overwritten.\n\nexport const CHECKOUT_HTML = ' + JSON.stringify(html) + ';\n');"
	@mkdir -p flutter/assets/icons && cp $(SHARED_ICONS_DIR)/*.svg flutter/assets/icons/
	@mkdir -p ios/Sources/BushaPay/Resources/icons && cp $(SHARED_ICONS_DIR)/*.svg ios/Sources/BushaPay/Resources/icons/
	@node -e "const fs=require('fs'),path=require('path');const dir='$(SHARED_ICONS_DIR)';const files=fs.readdirSync(dir).filter(f=>f.endsWith('.svg')).sort();const toConst=n=>n.replace(/\.svg$$/,'').replace(/-/g,'_').toUpperCase()+'_SVG';const body=files.map(f=>'export const '+toConst(f)+' = '+JSON.stringify(fs.readFileSync(path.join(dir,f),'utf8'))+';').join('\n\n');fs.writeFileSync('react-native/src/svg-icons.ts','// Auto-generated by \`make sync\` from '+dir+'/.\n// Do not edit by hand — changes will be overwritten.\n\n'+body+'\n');"

# Build each SDK
.PHONY: build-flutter build-android build-ios build-rn

build-flutter: sync
	cd flutter && flutter pub get && flutter analyze

build-android: sync
	cd android && ./gradlew :pay-android:assembleRelease

build-ios: sync
	cd ios && swift build

build-rn: sync
	cd react-native && yarn install --immutable && yarn prepare && yarn typecheck && yarn lint

# Publish
.PHONY: publish-flutter publish-android publish-ios publish-rn

publish-flutter: build-flutter
	cd flutter && flutter pub publish

publish-android: build-android
	cd android && ./gradlew :pay-android:publish

publish-ios:
	@echo "Tag and push — SPM picks it up from the Git tag"

publish-rn: build-rn
	cd react-native && yarn npm publish --access public

.PHONY: build-all publish-all clean
build-all: build-flutter build-android build-ios build-rn
publish-all: publish-flutter publish-android publish-ios publish-rn

clean:
	cd flutter && flutter clean || true
	cd android && ./gradlew clean || true
	cd ios && swift package clean || true
	cd react-native && rm -rf node_modules example/node_modules lib || true
