SHARED_HTML = shared/busha_pay_checkout.html
SHARED_ICONS_DIR = shared/icons

# Per-SDK sync targets so CI jobs only pull the tooling they need:
#   sync-flutter — plain `cp` (no extra deps)
#   sync-rn      — needs `node`
#   sync-ios     — needs `rsvg-convert` (`brew install librsvg`)
#   sync         — runs all three
.PHONY: sync sync-flutter sync-rn sync-ios

sync: sync-flutter sync-rn sync-ios

sync-flutter:
	@mkdir -p flutter/assets && cp $(SHARED_HTML) flutter/assets/busha_pay_checkout.html
	@mkdir -p flutter/assets/icons && cp $(SHARED_ICONS_DIR)/*.svg flutter/assets/icons/

sync-rn:
	@node -e "const fs=require('fs'); const html=fs.readFileSync('$(SHARED_HTML)','utf8'); fs.writeFileSync('react-native/src/checkout-html.ts', '// Auto-generated by \`make sync\` from $(SHARED_HTML).\n// Do not edit by hand — changes will be overwritten.\n\nexport const CHECKOUT_HTML = ' + JSON.stringify(html) + ';\n');"
	@node -e "const fs=require('fs'),path=require('path');const dir='$(SHARED_ICONS_DIR)';const files=fs.readdirSync(dir).filter(f=>f.endsWith('.svg')).sort();const toConst=n=>n.replace(/\.svg$$/,'').replace(/-/g,'_').toUpperCase()+'_SVG';const body=files.map(f=>'export const '+toConst(f)+' = '+JSON.stringify(fs.readFileSync(path.join(dir,f),'utf8'))+';').join('\n\n');fs.writeFileSync('react-native/src/svg-icons.ts','// Auto-generated by \`make sync\` from '+dir+'/.\n// Do not edit by hand — changes will be overwritten.\n\n'+body+'\n');"

sync-ios:
	@command -v rsvg-convert >/dev/null || { echo "rsvg-convert not found — install via 'brew install librsvg'"; exit 1; }
	@mkdir -p ios/Sources/BushaPay/Resources && cp $(SHARED_HTML) ios/Sources/BushaPay/Resources/busha_pay_checkout.html
	@for svg in $(SHARED_ICONS_DIR)/*.svg; do \
		base=$$(basename $$svg .svg); \
		dest=ios/Sources/BushaPay/Resources/Assets.xcassets/$$base.imageset; \
		mkdir -p $$dest; \
		rsvg-convert --format=pdf $$svg --output $$dest/$$base.pdf; \
		case $$base in \
			*-logo|*logo) intent=original ;; \
			*) intent=template ;; \
		esac; \
		printf '{\n  "images" : [\n    {\n      "filename" : "%s.pdf",\n      "idiom" : "universal"\n    }\n  ],\n  "info" : {\n    "author" : "xcode",\n    "version" : 1\n  },\n  "properties" : {\n    "preserves-vector-representation" : true,\n    "template-rendering-intent" : "%s"\n  }\n}\n' "$$base" "$$intent" > $$dest/Contents.json; \
	done

# Build each SDK
.PHONY: build-flutter build-android build-ios build-rn

build-flutter: sync-flutter
	cd flutter && flutter pub get && flutter analyze

build-android: sync
	cd android && ./gradlew :pay-android:assembleRelease

# `build-ios` is a compile-only smoke test, so a generic destination is
# fine and skips needing to boot or pick a specific simulator.
# `test-ios` actually runs XCTest, which requires a bootable destination —
# pick a simulator that ships with every modern Xcode. Override either
# with `make test-ios IOS_TEST_DESTINATION="…"`.
IOS_BUILD_DESTINATION ?= generic/platform=iOS Simulator
IOS_TEST_DESTINATION  ?= platform=iOS Simulator,name=iPhone 16,OS=latest

build-ios: sync-ios
	cd ios && xcodebuild -scheme BushaPay -destination "$(IOS_BUILD_DESTINATION)" build

test-ios: sync-ios
	cd ios && xcodebuild -scheme BushaPay -destination "$(IOS_TEST_DESTINATION)" test

build-rn: sync-rn
	cd react-native && yarn install --immutable && yarn prepare && yarn typecheck && yarn lint

# Publish
.PHONY: publish-flutter publish-android publish-ios publish-rn

publish-flutter: build-flutter
	cd flutter && flutter pub publish

publish-android: build-android
	cd android && ./gradlew :pay-android:publish

publish-ios:
	@echo "Tag and push — SPM picks it up from the Git tag"

publish-rn: build-rn
	cd react-native && yarn npm publish --access public

.PHONY: build-all publish-all clean
build-all: build-flutter build-android build-ios build-rn
publish-all: publish-flutter publish-android publish-ios publish-rn

clean:
	cd flutter && flutter clean || true
	cd android && ./gradlew clean || true
	cd ios && swift package clean || true
	cd react-native && rm -rf node_modules example/node_modules lib || true
