name: busha_pay
description: Official Busha Pay SDK for Flutter. Accept crypto payments in your app with a single integration.
version: 0.0.2
homepage: https://github.com/bushaHQ/busha-pay-flutter
repository: https://github.com/bushaHQ/busha-pay-flutter
issue_tracker: https://github.com/bushaHQ/busha-pay-flutter/issues

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.41.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_inappwebview: ^6.1.5
  flutter_svg: ^2.0.10
  url_launcher: ^6.3.1
  package_info_plus: ^8.1.3
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mocktail: ^1.0.4

flutter:
  assets:
    - assets/busha_pay_checkout.html
    - assets/icons/busha.svg
    - assets/icons/busha-logo.svg
    - assets/icons/wallet-outline.svg
